// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2HXJw44xFkH2UEXb3WSVNckSOufSU41s',
    appId: '1:298451019483:web:e1c3f34036f538ea7f4efe',
    messagingSenderId: '298451019483',
    projectId: 'liteharvest-68d43',
    authDomain: 'liteharvest-68d43.firebaseapp.com',
    databaseURL: 'https://liteharvest-68d43-default-rtdb.firebaseio.com',
    storageBucket: 'liteharvest-68d43.appspot.com',
    measurementId: 'G-HVNHXHWVZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_lnSk_keNK4S-jj1AhGDnDGjDcP0caqI',
    appId: '1:298451019483:android:2a863894a182dea87f4efe',
    messagingSenderId: '298451019483',
    projectId: 'liteharvest-68d43',
    databaseURL: 'https://liteharvest-68d43-default-rtdb.firebaseio.com',
    storageBucket: 'liteharvest-68d43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1CvUiOOFSzrhTppcy8kQ2P3F3QNHpjYc',
    appId: '1:298451019483:ios:203fc41003b00c7a7f4efe',
    messagingSenderId: '298451019483',
    projectId: 'liteharvest-68d43',
    databaseURL: 'https://liteharvest-68d43-default-rtdb.firebaseio.com',
    storageBucket: 'liteharvest-68d43.appspot.com',
    iosBundleId: 'com.example.liteHarvest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1CvUiOOFSzrhTppcy8kQ2P3F3QNHpjYc',
    appId: '1:298451019483:ios:203fc41003b00c7a7f4efe',
    messagingSenderId: '298451019483',
    projectId: 'liteharvest-68d43',
    databaseURL: 'https://liteharvest-68d43-default-rtdb.firebaseio.com',
    storageBucket: 'liteharvest-68d43.appspot.com',
    iosBundleId: 'com.example.liteHarvest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2HXJw44xFkH2UEXb3WSVNckSOufSU41s',
    appId: '1:298451019483:web:f504ee52eb59a9437f4efe',
    messagingSenderId: '298451019483',
    projectId: 'liteharvest-68d43',
    authDomain: 'liteharvest-68d43.firebaseapp.com',
    databaseURL: 'https://liteharvest-68d43-default-rtdb.firebaseio.com',
    storageBucket: 'liteharvest-68d43.appspot.com',
    measurementId: 'G-97119XVWPR',
  );
}
